from dataclasses import dataclass, field
from typing import Dict, List

@dataclass
class Circuit:
    name: str
    nodes: Dict[int, "Node"] = field(default_factory=dict)
    inputs: List[int] = field(default_factory=list)
    outputs: List[int] = field(default_factory=list)

    def add_node(self, node: "Node") -> None: ...
    def topological_order(self) -> list[int]: ...
    def fanin(self, nid: int) -> tuple[int, ...]: ...
    def fanout(self, nid: int) -> list[int]: ...
    def size(self) -> int: ...
    def depth(self) -> int: ...