from __future__ import annotations

from egglog import *


class Bit(Expr):
    def __init__(self, value: i64Like) -> None: ...
    @classmethod
    def var(cls, name: StringLike) -> Bit: ...
    def __and__(self, other: Bit) -> Bit: ...
    def __or__(self, other: Bit) -> Bit: ...
    def __invert__(self) -> Bit: ...
    def __xor__(self, other: Bit) -> Bit: ...